TRUNCATE TABLE dds.brand CASCADE;
TRUNCATE TABLE dds.category CASCADE;
TRUNCATE TABLE dds.product CASCADE;
TRUNCATE TABLE dds.transaction CASCADE;
TRUNCATE TABLE dds.stock CASCADE;
TRUNCATE TABLE dds.stores CASCADE;
