DROP SCHEMA IF EXISTS dds CASCADE;
DROP SCHEMA IF EXISTS dm CASCADE;
DROP SCHEMA IF EXISTS error CASCADE;
DROP SCHEMA IF EXISTS ref_info CASCADE;
        
CREATE SCHEMA IF NOT EXISTS dds;
CREATE SCHEMA IF NOT EXISTS dm;
CREATE SCHEMA IF NOT EXISTS error;
CREATE SCHEMA IF NOT EXISTS ref_info;